"""Database infrastructure — engine, session, and table constants."""

from .constants import (
    TABLE_NOVEL, TABLE_NOVEL_FTS, TABLE_AUTHOR, TABLE_SERIES,
    TABLE_TAG, TABLE_NOVEL_TAG, TABLE_FAVOURITE, TABLE_SPECIAL_FOLLOW,
    TABLE_FAILED_NOVEL, TABLE_SEARCH_HISTORY, TABLE_TASK_HISTORY,
    TABLE_SCHEDULED_TASK, TABLE_TAG_PREFERENCE, TABLE_TAG_ALIAS,
    TABLE_TOKEN,
    COL_ID, COL_TITLE, COL_AUTHOR_NAME, COL_AUTHOR_ID, COL_PATH,
    COL_LIKES, COL_VIEWS, COL_TEXTS, COL_CAPTION, COL_SERIES_ID,
    COL_SERIES_NAME, COL_SERIES_INDEX, COL_CREATE_TIME, COL_HAS_EPUB,
    COL_TAGS, COL_NOVEL_COUNT, COL_SOURCE,
    FIELD_KEYWORD, FIELD_TAGS, FIELD_IS_FAVOURITE, FIELD_IS_SPECIAL_FOLLOW,
    ORDER_BY_RANDOM, ORDER_BY_NONE,
)

__all__ = [
    "TABLE_NOVEL", "TABLE_NOVEL_FTS", "TABLE_AUTHOR", "TABLE_SERIES",
    "TABLE_TAG", "TABLE_NOVEL_TAG", "TABLE_FAVOURITE", "TABLE_SPECIAL_FOLLOW",
    "TABLE_FAILED_NOVEL", "TABLE_SEARCH_HISTORY", "TABLE_TASK_HISTORY",
    "TABLE_SCHEDULED_TASK", "TABLE_TAG_PREFERENCE", "TABLE_TAG_ALIAS",
    "TABLE_TOKEN",
]
