"""postgres greenfield baseline

Revision ID: 0001_postgres_baseline
Revises:
Create Date: 2026-08-31 20:40:00.000000

PostgreSQL-only initial schema (copixiv greenfield target,
``db_greenfield_design.md`` §4).  This is a multi-root baseline
(``down_revision=None``): the SQLite-era migrations were moved to
``alembic/legacy_sqlite/`` and are no longer part of the revision chain.

Notes / deliberate deviations from the design DDL:
- IDENTITY columns are ``GENERATED BY DEFAULT AS IDENTITY`` (the design used
  ``ALWAYS``) so the one-time SQLite→PG data migration can insert explicit
  ids for rows with FK dependents (e.g. ``tag.id`` referenced by
  ``tag_alias``) without ``OVERRIDING SYSTEM VALUE``.
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_postgres_baseline"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # 1) author / series
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE author (
            author_id          BIGINT PRIMARY KEY,
            author_name        TEXT,
            novel_count        INTEGER NOT NULL DEFAULT 0,
            "like"             INTEGER NOT NULL DEFAULT 0,
            "view"             INTEGER NOT NULL DEFAULT 0,
            "text"             INTEGER NOT NULL DEFAULT 0,
            last_update        TIMESTAMPTZ,
            is_special_follow  BOOLEAN NOT NULL DEFAULT FALSE
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_author_special_follow ON author (author_id) WHERE is_special_follow"
    )
    op.execute("CREATE INDEX ix_author_last_update ON author (last_update)")

    op.execute(
        """
        CREATE TABLE series (
            series_id          BIGINT PRIMARY KEY,
            series_name        TEXT,
            novel_count        INTEGER NOT NULL DEFAULT 0,
            author_id          BIGINT REFERENCES author(author_id) ON DELETE SET NULL,
            "like"             INTEGER NOT NULL DEFAULT 0,
            "view"             INTEGER NOT NULL DEFAULT 0,
            "text"             INTEGER NOT NULL DEFAULT 0
        )
        """
    )
    op.execute("CREATE INDEX ix_series_author_id ON series (author_id)")

    # ------------------------------------------------------------------
    # 2) novel (single table: list / search / flags / time)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE novel (
            id             BIGINT PRIMARY KEY,
            title          TEXT NOT NULL,
            author_id      BIGINT REFERENCES author(author_id),
            author_name    TEXT,
            path           TEXT UNIQUE,
            "like"         INTEGER NOT NULL DEFAULT 0,
            "view"         INTEGER NOT NULL DEFAULT 0,
            "text"         INTEGER NOT NULL DEFAULT 0,
            caption        TEXT,
            series_id      BIGINT REFERENCES series(series_id) ON DELETE SET NULL,
            series_name    TEXT,
            series_index   INTEGER,
            create_time    TIMESTAMPTZ,
            has_epub       INTEGER NOT NULL DEFAULT 0,
            shuffle        INTEGER NOT NULL DEFAULT 0,
            tags           TEXT[] NOT NULL DEFAULT '{}',
            is_favourite   BOOLEAN NOT NULL DEFAULT FALSE
        )
        """
    )
    op.execute("CREATE INDEX ix_novel_like_text_id ON novel (\"like\", \"text\", id)")
    op.execute("CREATE INDEX ix_novel_like_id ON novel (\"like\", id)")
    op.execute("CREATE INDEX ix_novel_shuffle_id ON novel (shuffle, id)")
    op.execute("CREATE INDEX ix_novel_shuffle_like_text ON novel (shuffle, \"like\", \"text\")")
    op.execute("CREATE INDEX ix_novel_author_id ON novel (author_id, id)")
    op.execute("CREATE INDEX ix_novel_series_id ON novel (series_id, id)")
    op.execute("CREATE INDEX ix_novel_author_like ON novel (author_id, \"like\")")
    op.execute("CREATE INDEX ix_novel_series_like ON novel (series_id, \"like\")")
    op.execute("CREATE INDEX ix_novel_create_time ON novel (create_time)")
    op.execute("CREATE INDEX ix_novel_tags_gin ON novel USING GIN (tags)")
    op.execute("CREATE INDEX ix_novel_favourite ON novel (id) WHERE is_favourite")

    # ------------------------------------------------------------------
    # 3) novel_search (application-maintained char-gram derived table)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE novel_search (
            novel_id     BIGINT PRIMARY KEY REFERENCES novel(id) ON DELETE CASCADE,
            search_text  TEXT NOT NULL
        )
        """
    )
    op.execute(
        "CREATE INDEX novel_search_gin ON novel_search USING GIN (to_tsvector('simple', search_text))"
    )

    # ------------------------------------------------------------------
    # 4) tag + reference_count trigger
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE tag (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name            TEXT NOT NULL UNIQUE,
            reference_count INTEGER NOT NULL DEFAULT 0
        )
        """
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION sync_tag_refs() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP IN ('DELETE','UPDATE') THEN
            UPDATE tag SET reference_count = reference_count - 1 WHERE name = ANY(OLD.tags);
          END IF;
          IF TG_OP IN ('INSERT','UPDATE') THEN
            INSERT INTO tag(name) SELECT DISTINCT unnest(NEW.tags) ON CONFLICT (name) DO NOTHING;
            UPDATE tag SET reference_count = reference_count + 1 WHERE name = ANY(NEW.tags);
          END IF;
          RETURN COALESCE(NEW, OLD);
        END; $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_sync_tag_refs AFTER INSERT OR UPDATE OR DELETE ON novel
          FOR EACH ROW EXECUTE FUNCTION sync_tag_refs();
        """
    )

    # ------------------------------------------------------------------
    # 5) tag_preference / tag_alias
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE tag_preference (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tag         TEXT NOT NULL UNIQUE,
            preference  TEXT NOT NULL CHECK (preference IN ('favourite','blocked')),
            sort_index  INTEGER NOT NULL DEFAULT 0
        )
        """
    )
    op.execute(
        """
        CREATE TABLE tag_alias (
            id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source  BIGINT NOT NULL UNIQUE REFERENCES tag(id),
            target  BIGINT NOT NULL REFERENCES tag(id)
        )
        """
    )
    op.execute("CREATE INDEX ix_tag_alias_target ON tag_alias (target)")

    # ------------------------------------------------------------------
    # 6) setting / scheduled_task / task_history / token / failed_novel /
    #    search_history
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE setting (
            key   TEXT PRIMARY KEY,
            value TEXT NOT NULL
        )
        """
    )
    op.execute(
        """
        CREATE TABLE scheduled_task (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name        TEXT NOT NULL,
            task        TEXT NOT NULL,
            cron        TEXT NOT NULL,
            params      JSONB,
            is_enabled  BOOLEAN NOT NULL DEFAULT FALSE,
            config      TEXT DEFAULT '{}',
            sort_index  INTEGER NOT NULL DEFAULT 0
        )
        """
    )
    op.execute(
        """
        CREATE TABLE task_history (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name        TEXT NOT NULL,
            task_func   TEXT,
            arguments   TEXT,
            status      TEXT NOT NULL,
            start_time  TIMESTAMPTZ NOT NULL,
            end_time    TIMESTAMPTZ,
            duration    DOUBLE PRECISION,
            result      JSONB,
            progress    JSONB
        )
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX ux_task_history_running ON task_history (task_func)
          WHERE status IN ('pending','running')
        """
    )
    op.execute(
        """
        CREATE TABLE token (
            id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name       TEXT NOT NULL UNIQUE,
            token      TEXT NOT NULL,
            premium    BOOLEAN NOT NULL DEFAULT FALSE,
            valid      BOOLEAN NOT NULL DEFAULT TRUE,
            sort_index INTEGER NOT NULL DEFAULT 0,
            is_follow  BOOLEAN NOT NULL DEFAULT FALSE
        )
        """
    )
    op.execute(
        """
        CREATE TABLE failed_novel (
            novel_id       BIGINT PRIMARY KEY,
            failure_type   TEXT,
            error_message  TEXT,
            failed_times   INTEGER NOT NULL DEFAULT 1,
            title          TEXT,
            last_failed_at TIMESTAMPTZ
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_failed_novel_last_failed_at ON failed_novel (last_failed_at)"
    )
    op.execute(
        """
        CREATE TABLE search_history (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type          TEXT NOT NULL,
            value         TEXT NOT NULL,
            display_value TEXT,
            timestamp     TIMESTAMPTZ NOT NULL,
            CONSTRAINT uq_search_history_type_value UNIQUE (type, value)
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_search_history_type_timestamp ON search_history (type, timestamp)"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_sync_tag_refs ON novel")
    op.execute("DROP FUNCTION IF EXISTS sync_tag_refs")
    for table in (
        "novel_search",
        "failed_novel",
        "novel",
        "series",
        "author",
        "tag_alias",
        "tag_preference",
        "task_history",
        "scheduled_task",
        "setting",
        "token",
        "search_history",
        "tag",
    ):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
