"""Repository protocols — abstract interfaces for data access."""

from typing import Protocol, runtime_checkable
from collections.abc import Sequence

from copixiv.domain.models.tag import Tag, TagPreference, TagAlias
from copixiv.domain.models.token import Token
from copixiv.domain.models.task import TaskHistory, ScheduledTask
from copixiv.domain.models.search import SearchHistory
from copixiv.domain.models.novel import EpubStatus
from copixiv.domain.services.parsing import SearchConditions


@runtime_checkable
class NovelRepository(Protocol):
    """Data access for novels."""

    async def get_by_id(self, novel_id: int) -> dict | None: ...
    async def get_novels(
        self,
        conditions: SearchConditions | None = None,
        order_by: str = "like",
        order_direction: str = "DESC",
        cursor: dict | None = None,
        per_page: int = 50,
        min_like: int | None = None,
        min_text: int | None = None,
    ) -> dict: ...
    async def count_novels(
        self,
        conditions: SearchConditions | None = None,
        min_like: int | None = None,
        min_text: int | None = None,
    ) -> int: ...
    async def upsert_novels(
        self, novels: list[dict], force_update: list[str] | None = None
    ) -> int: ...
    async def get_existing_ids(self, novel_ids: set[int]) -> set[int]: ...
    async def delete(self, novel_id: int) -> None: ...
    async def toggle_favourite(self, novel_id: int) -> None: ...
    async def toggle_special_follow(self, author_id: int) -> None: ...
    async def update_has_epub_status(
        self, novel_ids: list[int], status: EpubStatus
    ) -> None: ...
    async def update_field(self, novel_id: int, field: str, value: object) -> None: ...


@runtime_checkable
class AuthorRepository(Protocol):
    """Data access for authors."""

    def ensure_exists(self, author_ids: set[int]) -> None: ...
    async def get_by_id(self, author_id: int) -> dict | None: ...
    async def get_names_by_ids(self, author_ids: set[int]) -> dict[int, str]: ...
    async def need_update(self, author_id: int) -> bool: ...
    async def update_summary(self, author_ids: set[int]) -> None: ...
    async def update_last_update(self, author_id: int) -> None: ...
    async def update_author_name(self, author_id: int, name: str) -> None: ...
    async def delete_author_and_data(self, author_id: int) -> None: ...
    async def get_empty_author_ids(self) -> list[int]: ...
    async def get_special_follow_author_ids(self) -> list[int]: ...


@runtime_checkable
class SeriesRepository(Protocol):
    """Data access for series."""

    def ensure_exists(self, series_ids: set[int]) -> None: ...
    async def get_by_id(self, series_id: int) -> dict | None: ...
    async def update_summary(self, series_ids: set[int]) -> None: ...
    async def get_empty_series_ids(self) -> list[int]: ...
    async def series_with_empty_index(self) -> list[int]: ...


@runtime_checkable
class TagRepository(Protocol):
    """Data access for tags, preferences, and aliases."""

    # Tags
    async def get_all(self) -> Sequence[Tag]: ...
    async def rewrite_tags(self, novel_id: int, tags: set[str]) -> None: ...

    # Preferences
    async def get_preferences(self) -> Sequence[TagPreference]: ...
    async def create_preference(self, pref: TagPreference) -> TagPreference: ...
    async def update_preference(
        self, pref_id: int, pref: TagPreference
    ) -> TagPreference | None: ...
    async def delete_preference(self, pref_id: int) -> bool: ...
    async def reorder_preferences(self, ids: list[int]) -> bool: ...

    # Aliases
    async def get_aliases(self) -> Sequence[TagAlias]: ...
    async def get_alias_map(self) -> dict[str, str]: ...
    async def create_alias(self, alias: TagAlias) -> TagAlias: ...
    async def delete_alias(self, alias_id: int) -> bool: ...
    async def apply_alias_retroactively(self, source: str, target: str) -> int: ...


@runtime_checkable
class TokenRepository(Protocol):
    """Data access for Pixiv refresh tokens."""

    async def get_all(self) -> Sequence[Token]: ...
    async def get_by_name(self, name: str) -> Token | None: ...
    async def create(self, token: Token) -> Token: ...
    async def update(self, token_id: int, token: Token) -> Token | None: ...
    async def delete(self, token_id: int) -> bool: ...
    async def reorder(self, ids: list[int]) -> bool: ...


@runtime_checkable
class TaskRepository(Protocol):
    """Data access for task history and scheduling."""

    async def add_task(self, name: str, arguments: dict) -> int: ...
    async def update_task(
        self, task_id: int, status: str, result: str | None = None
    ) -> None: ...
    async def get_history(
        self, limit: int = 50, offset: int = 0
    ) -> Sequence[TaskHistory]: ...
    async def count_history(self) -> int: ...
    async def get_scheduled_tasks(self) -> Sequence[ScheduledTask]: ...
    async def create_scheduled(self, task: ScheduledTask) -> ScheduledTask: ...
    async def update_scheduled(
        self, task_id: int, task: ScheduledTask
    ) -> ScheduledTask | None: ...
    async def delete_scheduled(self, task_id: int) -> bool: ...
    async def reorder_scheduled(self, ids: list[int]) -> bool: ...


@runtime_checkable
class SearchHistoryRepository(Protocol):
    """Data access for search history."""

    async def get_all(
        self, limit: int = 50, offset: int = 0
    ) -> Sequence[SearchHistory]: ...
    async def add_or_update(
        self, type_: str, value: str, display_value: str | None = None
    ) -> None: ...
    async def delete(self, history_id: int) -> bool: ...
    async def clear_all(self) -> int: ...


@runtime_checkable
class FailedNovelRepositoryPort(Protocol):
    """Port for the download-failure ledger."""

    def record(self, novel_id: int, failure_type: str, error_message: str) -> None: ...
    def forget(self, novel_id: int) -> None: ...
    def forget_many(self, novel_ids: set[int]) -> None: ...
    def get_skip_ids(self, novel_ids: set[int]) -> set[int]: ...
